import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import SessionProvider from "@/components/shared/SessionProvider";
import ImageKitProvider from "@/components/shared/ImageKitProvider";
import { ThemeProvider } from "@/components/theme-provider";
import GoogleAnalytics from "@/components/shared/GoogleAnalytics";
import Loader from "@/components/animations/Loader";
import { getSettings } from "@/actions/settings.actions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function generateMetadata(): Promise<Metadata> {
  const settingsRes = await getSettings();
  const settings = settingsRes.data;

  const siteName = settings?.siteName || "CMS 3.0";
  const title = settings?.seoTitle || siteName;
  const description =
    settings?.siteDescription || "Generated by create next app";

  // Construct icons object conditionally
  const icons: any = {};
  if (settings?.faviconUrl) {
    icons.icon = settings.faviconUrl;
  }
  if (settings?.appleTouchIconUrl) {
    icons.apple = settings.appleTouchIconUrl;
  }

  return {
    title: {
      default: title,
      template: `%s | ${siteName}`,
    },
    description,
    icons: Object.keys(icons).length > 0 ? icons : undefined,
    openGraph: {
      title,
      description,
      siteName,
      images: settings?.seoImage ? [{ url: settings.seoImage }] : [],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: settings?.seoImage ? [settings.seoImage] : [],
    },
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settingsRes = await getSettings();
  const settings = settingsRes.success ? settingsRes.data : null;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {settings?.animations?.loader !== false &&
          settings?.animations?.global !== false && <Loader />}
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ImageKitProvider>
              {children}
              <GoogleAnalytics
                measurementId={process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}
              />
              <Toaster richColors position="top-center" />
            </ImageKitProvider>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
